/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;

import CONEXION.Conectividad;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    
    String dato;
    
    public Modificar() {
        initComponents();
        this.setTitle("Modificar");
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_form = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_mod = new javax.swing.JButton();
        txt_firma = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_escoger = new javax.swing.JButton();
        txt_tipo_seg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_cod_tit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_auto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_folio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_nit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Volver al menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MODIFICAR");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("1. Indique la tabla en la que desea modificar:");

        btn_form.setText("FORMULARIO");
        btn_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formActionPerformed(evt);
            }
        });

        jLabel3.setText("2. Ubica la fila que deseas modificar, luego haz click en escoger:");

        btn_mod.setText("Modificar");
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        jLabel5.setText("TIPO DE SEGURO:");

        btn_escoger.setText("Escoger");
        btn_escoger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escogerActionPerformed(evt);
            }
        });

        jLabel6.setText("NRO_FOLIO: ");

        jLabel7.setText("COD TITULAR:");

        jLabel8.setText("AUTORIZ. CORREO:");

        jLabel9.setText("FIRMA:");

        jLabel10.setText("NIT: ");

        jLabel4.setText("3. Llena los campos con los nuevos datos y luego haz click en modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_escoger)
                                .addGap(91, 91, 91))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(287, 287, 287)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(31, 31, 31)
                                        .addComponent(btn_form))
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_tipo_seg))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_cod_tit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txt_auto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txt_firma, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_folio)))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(123, 123, 123)
                                                .addComponent(jButton1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_mod)
                                                .addGap(19, 19, 19)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btn_form))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btn_escoger))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_tipo_seg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(txt_auto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mod)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_cod_tit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_folio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_firma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formActionPerformed
        // TODO add your handling code here:
        Conectividad f = new Conectividad(); 

        f.conectar(); 
        ResultSet r = f.consultar("select * from FORMULARIO"); 
        String sql;

        DefaultTableModel modelo = new DefaultTableModel(); 
        jTable1.setModel(modelo); 
         modelo.addColumn("N° EXPEDIENTE"); 
         modelo.addColumn("TIPO DE SEGURO"); 
         modelo.addColumn("N° FOLIO"); 
         modelo.addColumn("N° DOC TITULAR"); 
         modelo.addColumn("AUTO. CORREO");
         modelo.addColumn("FIRMA ESSALUD");
         modelo.addColumn("NIT ESSALUD");
         
         try { 
            while(r.next()){ 
               Object [] fila = new Object[7];//Crea un vector 
               //para almacenar los valores del ResultSet 
              for (int i=0;i<7;i++) 
              fila[i] = r.getObject(i+1); // El primer indice en rs es el 1, no el cero, por eso se suma 1. 
               //añado el modelo a la tabla 
               modelo.addRow(fila); 
               fila=null;//limpia los datos de el vector de la memoria 
            } 
            r.close();//cerrar result-set 
        } catch (SQLException ex) { 
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        } 
        /*DefaultTableModel tm = (DefaultTableModel) jTable1.getModel(); 
        dato=String.valueOf(tm.getValueAt(jTable1.getSelectedRow()+1,0));
        System.out.println(dato);*/
        
    }//GEN-LAST:event_btn_formActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        // TODO add your handling code here:
        Conectividad f = new Conectividad(); 
        f.conectar(); 
        String sql1,sql2,sql3,sql4,sql5,sql6;
        
        if(!"".equals(txt_tipo_seg.getText())){
            sql1 = "UPDATE FORMULARIO SET tipo_seg='"+txt_tipo_seg.getText()+"'where nro_form='"+dato+"'";
            boolean k = f.escribir(sql1);
        }
        if(!"".equals(txt_folio.getText())){
            sql2 = "UPDATE FORMULARIO SET nro_folio="+Integer.parseInt(txt_folio.getText())+"where nro_form='"+dato+"'";
            boolean k = f.escribir(sql2);
        }
        if(!"".equals(txt_cod_tit.getText())){
            sql3 = "UPDATE FORMULARIO SET cod_tit_form='"+txt_cod_tit.getText()+"'where nro_form='"+dato+"'";
            boolean k = f.escribir(sql3);
        }
        if(!"".equals(txt_auto.getText())){
            sql4 = "UPDATE FORMULARIO SET aut_correo='"+txt_auto.getText()+"'where nro_form='"+dato+"'";
            boolean k = f.escribir(sql4);
        }
        if(!"".equals(txt_firma.getText())){
            sql5 = "UPDATE FORMULARIO SET firma_essalud='"+txt_firma.getText() +"' where nro_form='"+dato+"'";
            boolean k = f.escribir(sql5);
        }
        if(!"".equals(txt_nit.getText())){
            sql6 = "UPDATE FORMULARIO SET nit_essalud='"+txt_nit.getText()+"' where nro_form='"+dato+"'";
            boolean k = f.escribir(sql6);
        }
        //sql = "UPDATE FORMULARIO SET tipo_seg='"+txt_tipo_seg.getText()+"' , nro_folio="+Integer.parseInt(txt_folio.getText())+", cod_tit_form='"+txt_cod_tit.getText()+"', aut_correo='"+txt_auto.getText()+"', firma_essalud='"+txt_firma.getText() +"', nit_essalud='"+txt_nit.getText()+"' where nro_form='"+dato+"'";
        //f.conectar(); 
        //boolean k = f.escribir(sql); 
        
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_escogerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escogerActionPerformed
        // TODO add your handling code here:
        int row1= jTable1.getSelectedRow();
        System.out.println(row1);
        dato=(String) jTable1.getValueAt(row1, 0);
        System.out.println(dato);
    }//GEN-LAST:event_btn_escogerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_escoger;
    private javax.swing.JButton btn_form;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_auto;
    private javax.swing.JTextField txt_cod_tit;
    private javax.swing.JTextField txt_firma;
    private javax.swing.JTextField txt_folio;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_tipo_seg;
    // End of variables declaration//GEN-END:variables
}
