
package FORMULARIOS;

import CONEXION.Conectividad;
import ENTIDADES.*;
import java.awt.Color;
import javax.swing.JOptionPane;

public class Paso2_Solicitud extends javax.swing.JFrame {
    
    static Documento doc_tit_form;
    static Documento doc_emp_form;
    Documento doc_der= new Documento();
    Documento doc_sol=new Documento();
    Persona per= new Persona();
    Derechohabiente der= new Derechohabiente();
    Titular tit= new Titular();
    Detalle_Latencia det_lat= new Detalle_Latencia();
    Detalle_Prest_Eco det_prest_eco = new Detalle_Prest_Eco();
    Detalle_Registro det_reg =new Detalle_Registro();
    Solicitante sol= new Solicitante();
    Empleador emp= new Empleador();
    

    public Paso2_Solicitud(Documento d_tit, Documento d_emp) {
        initComponents();
        this.setTitle("Formulario-Paso2");
        this.getContentPane().setBackground(Color.WHITE);
        doc_tit_form=d_tit;
        doc_emp_form=d_emp;
        JOptionPane.showMessageDialog(rootPane,"Recuerde que si Ud es asegurado"
                + " titular y es la primera vez\nque llena el formulario, se "
                + "debe inscribir(registrar) llenando los campos\nsolicitados en "
                + "el tipo de registro ALTA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngper = new javax.swing.ButtonGroup();
        rbtngtiporeg = new javax.swing.ButtonGroup();
        rbtnggen = new javax.swing.ButtonGroup();
        rbtngtippag = new javax.swing.ButtonGroup();
        rbtngvinlab = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbtn_tit = new javax.swing.JRadioButton();
        rbtn_der = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtn_alta = new javax.swing.JRadioButton();
        rbtn_actual = new javax.swing.JRadioButton();
        rbtn_baja = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_tipo_doc = new javax.swing.JComboBox<>();
        txt_nro_doc_reg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmb_vin_tit_der = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_ap_pat_per = new javax.swing.JTextField();
        txt_ap_mat_per = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_ap_cas_per = new javax.swing.JTextField();
        txt_nom_per = new javax.swing.JTextField();
        rbtn_fem = new javax.swing.JRadioButton();
        rbtn_masc = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        cmb_est_civ_per = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txt_fech_nac_per = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_telf_per = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_cor_per = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_via = new javax.swing.JTextField();
        txt_num = new javax.swing.JTextField();
        txt_depart = new javax.swing.JTextField();
        txt_int = new javax.swing.JTextField();
        txt_mz = new javax.swing.JTextField();
        txt_lote = new javax.swing.JTextField();
        txt_km = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_bloq = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_etap = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_zona = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_dep = new javax.swing.JTextField();
        txt_prov = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_distr = new javax.swing.JTextField();
        txt_ref = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txt_nom_emp = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_fech_susp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_si_vin_lab = new javax.swing.JRadioButton();
        txt_no_vin_lab = new javax.swing.JRadioButton();
        rbtn_pag_dir = new javax.swing.JRadioButton();
        rbtn_reem = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        cmb_tip_tram = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        txt_nom_sol = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        cmb_tip_doc_sol = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        txt_num_doc_sol = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txt_telf_sol = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txt_cor_sol = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txt_fech_ini_sol = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txt_fech_fin_sol = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txt_dias_subs_sol = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txt_mont_sub_sol = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        cmb_vin_sol = new javax.swing.JComboBox<>();
        btn_continuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("II. SOLICITUD");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Persona:");

        rbtngper.add(rbtn_tit);
        rbtn_tit.setText("Titular");
        rbtn_tit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_titActionPerformed(evt);
            }
        });

        rbtngper.add(rbtn_der);
        rbtn_der.setText("Derechohabiente");
        rbtn_der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_derActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de Registro:");

        rbtngtiporeg.add(rbtn_alta);
        rbtn_alta.setText("Alta");

        rbtngtiporeg.add(rbtn_actual);
        rbtn_actual.setText("Actualización");

        rbtngtiporeg.add(rbtn_baja);
        rbtn_baja.setText("Baja");

        jLabel4.setText("Datos de la Persona a Registrar:");

        jLabel5.setText("Tipo de documento: ");

        jLabel6.setText("Número:");

        cmb_tipo_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "ACTA DE NACIMIENTO", "CARNET DE EXTRANJERÍA", "PASAPORTE" }));
        cmb_tipo_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipo_docActionPerformed(evt);
            }
        });

        txt_nro_doc_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nro_doc_regActionPerformed(evt);
            }
        });

        jLabel7.setText("Vínculo con el titular:");

        cmb_vin_tit_der.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cónyuge", "Concubino", "Hijo mayor incapacitado", "Hijo", "Madre Gestante(Hijo Extramatrimonial)" }));
        cmb_vin_tit_der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_vin_tit_derActionPerformed(evt);
            }
        });

        jLabel8.setText("Apellido Paterno:");

        jLabel9.setText("Apellido Materno:");

        txt_ap_pat_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ap_pat_perActionPerformed(evt);
            }
        });

        txt_ap_mat_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ap_mat_perActionPerformed(evt);
            }
        });

        jLabel10.setText("Apellido de Casada:");

        jLabel11.setText("Nombre(s):");

        jLabel12.setText("Género:");

        txt_ap_cas_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ap_cas_perActionPerformed(evt);
            }
        });

        rbtnggen.add(rbtn_fem);
        rbtn_fem.setText("Femenino");

        rbtnggen.add(rbtn_masc);
        rbtn_masc.setText("Masculino");

        jLabel13.setText("Estado Civil:");

        cmb_est_civ_per.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero(a)", "Casado(a)", "Viudo(a)", "Divorciado(a)" }));
        cmb_est_civ_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_est_civ_perActionPerformed(evt);
            }
        });

        jLabel14.setText("Fecha de nacimiento:");

        jLabel15.setText("N° Teléfono o Celular:");

        jLabel16.setText("Correo Electrónico:");

        jLabel17.setText("Dirección(Opcional):");

        jLabel18.setText("Nombre de la vía:");

        jLabel19.setText("Número:");

        jLabel20.setText("Departamento:");

        jLabel21.setText("Interior:");

        jLabel22.setText("Manzana:");

        jLabel23.setText("N° Lote:");

        jLabel24.setText("N° KM:");

        jLabel25.setText("N° Bloque:");

        txt_bloq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bloqActionPerformed(evt);
            }
        });

        jLabel26.setText("N° Etapa:");

        jLabel27.setText("Nombre de la Zona:");

        jLabel28.setText("Departamento:");

        jLabel29.setText("Provincia:");

        jLabel30.setText("Distrito:");

        jLabel31.setText("Referencia:");

        txt_distr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_distrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtn_alta)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_actual)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_baja))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_tit)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_der)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel21)
                                                    .addComponent(jLabel22)
                                                    .addComponent(jLabel27)
                                                    .addComponent(jLabel28)
                                                    .addComponent(jLabel29)
                                                    .addComponent(jLabel30)
                                                    .addComponent(jLabel31))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txt_distr, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_prov, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_dep, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_zona, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_ref)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(txt_int)
                                                                    .addComponent(txt_depart)
                                                                    .addComponent(txt_num)
                                                                    .addComponent(txt_mz, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                                                .addGap(47, 47, 47)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel26)
                                                                        .addGap(22, 22, 22)
                                                                        .addComponent(txt_etap, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel25)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(txt_bloq))
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                            .addComponent(jLabel24)
                                                                            .addComponent(jLabel23))
                                                                        .addGap(25, 25, 25)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                            .addComponent(txt_km, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                                                            .addComponent(txt_lote)))))
                                                            .addComponent(txt_via, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(44, 44, 44)))))
                                .addGap(0, 19, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtn_fem)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_masc))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_vin_tit_der, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_ap_mat_per, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(txt_ap_pat_per, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_tipo_doc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_nro_doc_reg))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ap_cas_per)
                            .addComponent(txt_nom_per, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txt_cor_per)
                            .addComponent(txt_telf_per)
                            .addComponent(txt_fech_nac_per)
                            .addComponent(cmb_est_civ_per, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbtn_tit)
                    .addComponent(rbtn_der))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtn_alta)
                    .addComponent(rbtn_actual)
                    .addComponent(rbtn_baja))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmb_tipo_doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_nro_doc_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmb_vin_tit_der, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_ap_pat_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_ap_mat_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_ap_cas_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_nom_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(rbtn_fem)
                            .addComponent(rbtn_masc))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13))
                    .addComponent(cmb_est_civ_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(txt_fech_nac_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_telf_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_cor_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(txt_via, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(txt_lote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(txt_km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txt_depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_bloq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(txt_int, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_mz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txt_etap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_zona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt_distr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txt_ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("REGISTRO", jScrollPane1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel32.setText("Nombre o Razón Social de la Entidad empleadora:");

        jLabel33.setText("Fecha de cese o suspensión:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(txt_nom_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_fech_susp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(txt_nom_emp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(txt_fech_susp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LATENCIA", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel34.setText("Tipo de Pago:");

        jLabel35.setText("Asegurado Titular con Vínculo");

        jLabel36.setText("laboral a la fecha de contingencia:");

        rbtngvinlab.add(txt_si_vin_lab);
        txt_si_vin_lab.setText("Sí");
        txt_si_vin_lab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_si_vin_labActionPerformed(evt);
            }
        });

        rbtngvinlab.add(txt_no_vin_lab);
        txt_no_vin_lab.setText("No");

        rbtngtippag.add(rbtn_pag_dir);
        rbtn_pag_dir.setText("Pago Directo");
        rbtn_pag_dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_pag_dirActionPerformed(evt);
            }
        });

        rbtngtippag.add(rbtn_reem);
        rbtn_reem.setText("Reembolso");

        jLabel37.setText("Tipo de Trámite:");

        cmb_tip_tram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lactancia", "Sepelio", "Maternidad", "Incapacidad" }));

        jLabel38.setText("Solicitante o Beneficiario:");

        jLabel39.setText("Tipo de Documento:");

        cmb_tip_doc_sol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "CE", "RUC" }));

        jLabel40.setText("Número:");

        txt_num_doc_sol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num_doc_solActionPerformed(evt);
            }
        });

        jLabel41.setText("Teléfono:");

        jLabel42.setText("Correo:");

        jLabel43.setText("Fecha de Inicio: ");

        jLabel44.setText("Fecha de Fín:");

        jLabel45.setText("Días Subsidiados:");

        jLabel46.setText("Monto a Subsidiar:");

        jLabel47.setText("Vínculo del Solicitante con el titular:");

        cmb_vin_sol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Titular", "Cónyuge/Concubino", "Padre/Madre no asegurado", "Tutor", "Curador" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_tip_doc_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_num_doc_sol))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nom_sol, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(42, 42, 42)
                                .addComponent(cmb_tip_tram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(44, 44, 44)
                                .addComponent(rbtn_pag_dir)
                                .addGap(52, 52, 52)
                                .addComponent(rbtn_reem))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel35))
                                .addGap(34, 34, 34)
                                .addComponent(txt_si_vin_lab)
                                .addGap(32, 32, 32)
                                .addComponent(txt_no_vin_lab))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel42))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_telf_sol, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cor_sol, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel44))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_fech_ini_sol)
                                    .addComponent(txt_fech_fin_sol, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_dias_subs_sol)
                                .addGap(273, 273, 273))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_vin_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(18, 18, 18)
                        .addComponent(txt_mont_sub_sol, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(334, 334, 334))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(rbtn_pag_dir)
                    .addComponent(rbtn_reem))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_si_vin_lab)
                        .addComponent(txt_no_vin_lab)))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cmb_tip_tram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txt_nom_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(cmb_tip_doc_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(txt_num_doc_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txt_telf_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txt_cor_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txt_fech_ini_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txt_fech_fin_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(txt_dias_subs_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(txt_mont_sub_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(cmb_vin_sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        jTabbedPane1.addTab("PRESTACIONES ECONÓMICAS", jScrollPane2);

        btn_continuar.setText("CONTINUAR");
        btn_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_continuar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_continuar)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continuarActionPerformed
        // TODO add your handling code here:
        
        tit.setNro_doc_per(doc_tit_form.getNro_doc());
        emp.setNro_doc_emp(doc_emp_form.getNro_doc());
        emp.setCod_emp(emp.getNro_doc_emp()+ " - EMP");
        tit.setCod_emp_tit(emp.getCod_emp());
        tit.setCod_aseg(tit.getNro_doc_per()+" - TIT");
        tit.setEst_lab_tit("Activo");
        if(rbtn_tit.isSelected()){
            det_reg.setTipo_per_sol("Titular");
            per.setNro_doc_per(doc_tit_form.getNro_doc());
            tit.setAp_pat_per(txt_ap_pat_per.getText());
            per.setCod_aseg(tit.getNro_doc_per()+" - TIT");
   
        }else{
            if(rbtn_der.isSelected()){
                
                det_reg.setTipo_per_sol("Derechohabiente");
                der.setNro_doc_per(txt_nro_doc_reg.getText());
                per.setNro_doc_per(txt_nro_doc_reg.getText());
                der.setAp_pat_per(txt_ap_pat_per.getText());
                per.setCod_aseg(der.getNro_doc_per()+" - DER");
                der.setCod_aseg(der.getNro_doc_per()+" - DER");
                der.setCod_tit_der(tit.getCod_aseg());
                doc_der.setNro_doc(txt_nro_doc_reg.getText());
                if(cmb_tipo_doc.getSelectedIndex()==0){
                    doc_der.setTipo_doc("DNI");
                    doc_der.setNom_comp_doc("Documento Nacional de identidad");
                }else{
                   if(cmb_tipo_doc.getSelectedIndex()==1){
                           doc_der.setTipo_doc("AN");
                           doc_der.setNom_comp_doc("Acta de Nacimiento");
                   }else{
                       if(cmb_tipo_doc.getSelectedIndex()==2){
                           doc_der.setTipo_doc("CE");
                           doc_der.setNom_comp_doc("Carnet de Extranjería");
                       }else{
                           if(cmb_tipo_doc.getSelectedIndex()==3){
                               doc_der.setTipo_doc("PAS");
                               doc_der.setNom_comp_doc("Pasaporte");
                           }
                       }       
                   }
               }
                if(cmb_vin_tit_der.getSelectedIndex()==0){
                           der.setVin_tit_per_reg("Cónyuge");
                   }else{
                       if(cmb_vin_tit_der.getSelectedIndex()==1){
                           der.setVin_tit_per_reg("Concubino");                 
                       }else{
                           if(cmb_vin_tit_der.getSelectedIndex()==2){
                           der.setVin_tit_per_reg("Hijo Mayor Incapacitado");
                            }
                           else{
                               if(cmb_vin_tit_der.getSelectedIndex()==3){
                                    der.setVin_tit_per_reg("Hijo");
                                }else{
                                   if(cmb_vin_tit_der.getSelectedIndex()==4){
                                        der.setVin_tit_per_reg("Madre Gestante(Hijo Extramatrimonial)");
                                    }
                               }
                           }
                       }       
                   }
               
            }
        }
        if(rbtn_alta.isSelected()){
            det_reg.setTipo_reg("Alta");
        }else{
            if(rbtn_actual.isSelected()){
                det_reg.setTipo_reg("Actualización");
            }else{
                if(rbtn_baja.isSelected()){
                    det_reg.setTipo_reg("Baja");
                }
            }
        }
        per.setAp_pat_per(txt_ap_pat_per.getText());
        per.setAp_mat_per(txt_ap_mat_per.getText());
        per.setNom_per(txt_nom_per.getText());
        if(rbtn_fem.isSelected()){
            per.setGen_per("F");
        }else{
           if(rbtn_masc.isSelected()){
                per.setGen_per("M");
            } 
        }
        if(cmb_est_civ_per.getSelectedIndex()==0){
           per.setEst_civil_per("S");
        }else{
           if(cmb_est_civ_per.getSelectedIndex()==1){
                per.setEst_civil_per("C");
           }else{
               if(cmb_est_civ_per.getSelectedIndex()==2){
                    per.setEst_civil_per("V");
                }else{
                   if(cmb_est_civ_per.getSelectedIndex()==3){
                        per.setEst_civil_per("D");
                    }
               }
           }
        }
        if("C".equals(per.getEst_civil_per()) && "F".equals(per.getGen_per())){
            per.setAp_cas_per(txt_ap_cas_per.getText());
        }    
        if(!"".equals(txt_telf_per.getText())){
            per.setTelf_per(Integer.parseInt(txt_telf_per.getText()));
        }
        if(!"".equals(txt_num.getText())){
            per.setNum_dir_per(Integer.parseInt(txt_num.getText()));
        }
        if(!"".equals(txt_depart.getText())){
            per.setDepa_dir_per(Integer.parseInt(txt_depart.getText()));
        }
        if(!"".equals(txt_int.getText())){
            per.setInt_dir_per(Integer.parseInt(txt_int.getText()));
        }
        if(!"".equals(txt_lote.getText())){
            per.setLote_dir_per(Integer.parseInt(txt_lote.getText()));
        }
        if(!"".equals(txt_km.getText())){
            per.setKm_dir_per((Integer.parseInt(txt_km.getText())));
        }
        if(!"".equals(txt_bloq.getText())){
             per.setBlock_dir_per((Integer.parseInt(txt_bloq.getText())));
        }
        if(!"".equals(txt_etap.getText())){
            per.setEtap_dir_per((Integer.parseInt(txt_etap.getText())));
        }
        per.setCorreo_per(txt_cor_per.getText());
        per.setFech_nac_per(txt_fech_nac_per.getText());
        per.setVia_per_dir(txt_via.getText());    
        per.setMz_dir_per(txt_mz.getText());
        per.setZon_dir_per(txt_zona.getText());
        per.setDep_dir_per(txt_dep.getText());
        per.setProv_dir_per(txt_prov.getText());
        per.setDist_dir_per(txt_distr.getText());
        per.setRef_dir_per(txt_ref.getText());
        det_lat.setFech_susp_emp(txt_fech_susp.getText());
        if(txt_fech_susp.getText()==null){tit.setEst_lab_tit("Inactivo");}
        if(rbtn_pag_dir.isSelected()){
            det_prest_eco.setTipo_pago_prest("Pago Directo");
        }else{
            if(rbtn_reem.isSelected()){
                det_prest_eco.setTipo_pago_prest("Reembolso");
            }
        }
        if(txt_si_vin_lab.isSelected()){
            tit.setEst_lab_tit("Activo");
        }else{
            if(txt_si_vin_lab.isSelected()){
                tit.setEst_lab_tit("Inactivo");
            }
        }
        if(cmb_tip_tram.getSelectedIndex()==0){
            det_prest_eco.setTipo_tram_prest("Lactancia");
        }else{
            if(cmb_tip_tram.getSelectedIndex()==1){
                det_prest_eco.setTipo_tram_prest("Sepelio");
            }else{
                if(cmb_tip_tram.getSelectedIndex()==2){
                    det_prest_eco.setTipo_tram_prest("Maternidad");
                }else{
                    if(cmb_tip_tram.getSelectedIndex()==3){
                        det_prest_eco.setTipo_tram_prest("Incapacidad");
                    }
                }
            }
        }
        sol.setCod_tit_bene(tit.getCod_aseg());
        sol.setNom_bene_prest(txt_nom_sol.getText());
        if(cmb_tip_doc_sol.getSelectedIndex()==0){
            doc_sol.setTipo_doc("DNI");
            doc_sol.setNom_comp_doc("Documento nacional de identidad");
        }else{
            if(cmb_tip_doc_sol.getSelectedIndex()==1){
                doc_sol.setTipo_doc("CE");
                doc_sol.setNom_comp_doc("Carnet de Extranjería");
            }else{
                if(cmb_tip_doc_sol.getSelectedIndex()==2){
                    doc_sol.setTipo_doc("RUC");
                    doc_sol.setNom_comp_doc("Registro Único de Contribuyentes");
                }
            }
        }
        sol.setNro_doc_bene_prest(txt_num_doc_sol.getText());
        doc_sol.setNro_doc(txt_num_doc_sol.getText());
        if(!"".equals(txt_telf_sol.getText())){
            sol.setTelf_bene_prest(Integer.parseInt(txt_telf_sol.getText()));
        }      
        sol.setCorreo_bene_prest(txt_cor_sol.getText());
        if(cmb_vin_sol.getSelectedIndex()==0){
            sol.setVin_bene_prest("Titular");
        }else{
            if(cmb_vin_sol.getSelectedIndex()==1){
                sol.setVin_bene_prest("Cónyuge/Concubino");
            }else{
                if(cmb_vin_sol.getSelectedIndex()==2){
                    sol.setVin_bene_prest("Padre/madre no asegurado");
                }else{
                    if(cmb_vin_sol.getSelectedIndex()==3){
                        sol.setVin_bene_prest("Tutor");
                    }else{
                        if(cmb_vin_sol.getSelectedIndex()==4){
                            sol.setVin_bene_prest("Curador");
                        }
                    }
                }
            }
        }
        det_prest_eco.setFech_ini_bene_prest(txt_fech_ini_sol.getText());
        det_prest_eco.setFech_fin_bene_prest(txt_fech_fin_sol.getText());
        if(!"".equals(txt_dias_subs_sol.getText())){
            det_prest_eco.setDias_subs_bene_prest(Integer.parseInt(txt_dias_subs_sol.getText()));
        }
        if(!"".equals(txt_mont_sub_sol.getText())){
            
            det_prest_eco.setMonto_subs(Integer.parseInt(txt_mont_sub_sol.getText()));
        }
        
        //System.out.println(doc_tit_form.getNro_doc()+doc_emp_form.getTipo_doc());
        
        
        if(doc_der.getNro_doc()!=null){
            Conectividad fun=new Conectividad(); 
            fun.conectar();
            String  sql2;
            sql2 ="INSERT INTO DOCUMENTO VALUES ('"+ doc_der.getNro_doc()+"','"+ doc_der.getTipo_doc()+"','"+ doc_der.getNom_comp_doc()+"')";            
            insertar(sql2, fun);          
        }
        if(doc_sol.getNro_doc()!=null){
            Conectividad fun=new Conectividad(); 
            fun.conectar();
            String  sql2;
            sql2 ="INSERT INTO DOCUMENTO VALUES ('"+ doc_sol.getNro_doc()+"','"+ doc_sol.getTipo_doc()+"','"+ doc_sol.getNom_comp_doc()+"')";
            insertar(sql2, fun);
        }
        
        Paso3_Declaracion p3= new Paso3_Declaracion(per,der,tit,det_lat,det_prest_eco,det_reg,sol,emp);
        p3.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_continuarActionPerformed

    private void insertar(String cad, Conectividad f){
        boolean k = f.escribir(cad); 
    }
    
    private void rbtn_titActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_titActionPerformed
        // TODO add your handling code here:
        if(rbtn_tit.isSelected()){
            cmb_tipo_doc.setVisible(false);
            txt_nro_doc_reg.setVisible(false);
            cmb_vin_tit_der.setVisible(false);
        }
    }//GEN-LAST:event_rbtn_titActionPerformed

    private void txt_nro_doc_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nro_doc_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nro_doc_regActionPerformed

    private void txt_ap_mat_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ap_mat_perActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ap_mat_perActionPerformed

    private void txt_ap_pat_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ap_pat_perActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ap_pat_perActionPerformed

    private void txt_si_vin_labActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_si_vin_labActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_si_vin_labActionPerformed

    private void rbtn_pag_dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_pag_dirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_pag_dirActionPerformed

    private void txt_bloqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bloqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bloqActionPerformed

    private void txt_distrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_distrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_distrActionPerformed

    private void cmb_tipo_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipo_docActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipo_docActionPerformed

    private void cmb_vin_tit_derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_vin_tit_derActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_vin_tit_derActionPerformed

    private void rbtn_derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_derActionPerformed
        // TODO add your handling code here:
        if(rbtn_der.isSelected()){
            cmb_tipo_doc.setVisible(true);
            txt_nro_doc_reg.setVisible(true);
            cmb_vin_tit_der.setVisible(true);
        }
    }//GEN-LAST:event_rbtn_derActionPerformed

    private void cmb_est_civ_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_est_civ_perActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_est_civ_perActionPerformed

    private void txt_ap_cas_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ap_cas_perActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_ap_cas_perActionPerformed

    private void txt_num_doc_solActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num_doc_solActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num_doc_solActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paso2_Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paso2_Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paso2_Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paso2_Solicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paso2_Solicitud(doc_tit_form, doc_emp_form).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_continuar;
    private javax.swing.JComboBox<String> cmb_est_civ_per;
    private javax.swing.JComboBox<String> cmb_tip_doc_sol;
    private javax.swing.JComboBox<String> cmb_tip_tram;
    private javax.swing.JComboBox<String> cmb_tipo_doc;
    private javax.swing.JComboBox<String> cmb_vin_sol;
    private javax.swing.JComboBox<String> cmb_vin_tit_der;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbtn_actual;
    private javax.swing.JRadioButton rbtn_alta;
    private javax.swing.JRadioButton rbtn_baja;
    private javax.swing.JRadioButton rbtn_der;
    private javax.swing.JRadioButton rbtn_fem;
    private javax.swing.JRadioButton rbtn_masc;
    private javax.swing.JRadioButton rbtn_pag_dir;
    private javax.swing.JRadioButton rbtn_reem;
    private javax.swing.JRadioButton rbtn_tit;
    private javax.swing.ButtonGroup rbtnggen;
    private javax.swing.ButtonGroup rbtngper;
    private javax.swing.ButtonGroup rbtngtiporeg;
    private javax.swing.ButtonGroup rbtngtippag;
    private javax.swing.ButtonGroup rbtngvinlab;
    private javax.swing.JTextField txt_ap_cas_per;
    private javax.swing.JTextField txt_ap_mat_per;
    private javax.swing.JTextField txt_ap_pat_per;
    private javax.swing.JTextField txt_bloq;
    private javax.swing.JTextField txt_cor_per;
    private javax.swing.JTextField txt_cor_sol;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_depart;
    private javax.swing.JTextField txt_dias_subs_sol;
    private javax.swing.JTextField txt_distr;
    private javax.swing.JTextField txt_etap;
    private javax.swing.JTextField txt_fech_fin_sol;
    private javax.swing.JTextField txt_fech_ini_sol;
    private javax.swing.JTextField txt_fech_nac_per;
    private javax.swing.JTextField txt_fech_susp;
    private javax.swing.JTextField txt_int;
    private javax.swing.JTextField txt_km;
    private javax.swing.JTextField txt_lote;
    private javax.swing.JTextField txt_mont_sub_sol;
    private javax.swing.JTextField txt_mz;
    private javax.swing.JRadioButton txt_no_vin_lab;
    private javax.swing.JTextField txt_nom_emp;
    private javax.swing.JTextField txt_nom_per;
    private javax.swing.JTextField txt_nom_sol;
    private javax.swing.JTextField txt_nro_doc_reg;
    private javax.swing.JTextField txt_num;
    private javax.swing.JTextField txt_num_doc_sol;
    private javax.swing.JTextField txt_prov;
    private javax.swing.JTextField txt_ref;
    private javax.swing.JRadioButton txt_si_vin_lab;
    private javax.swing.JTextField txt_telf_per;
    private javax.swing.JTextField txt_telf_sol;
    private javax.swing.JTextField txt_via;
    private javax.swing.JTextField txt_zona;
    // End of variables declaration//GEN-END:variables
}
