/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;

import CONEXION.Conectividad;
import ENTIDADES.*;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class Paso4_UsodeEssalud extends javax.swing.JFrame {

    static Persona per4;
    static Derechohabiente der4;
    static Titular tit4;
    static Detalle_Latencia det_lat4;
    static Detalle_Prest_Eco det_prest_eco4;
    static Detalle_Registro det_reg4;
    static Solicitante sol4;
    static Empleador emp4;
    static Formulario f4;
    
    public Paso4_UsodeEssalud(Persona p, Derechohabiente d, Titular t, Detalle_Latencia dl, Detalle_Prest_Eco dp, Detalle_Registro dr, Solicitante s, Empleador e,Formulario f) {
        initComponents();
        this.setTitle("Formulario-Paso4");
        this.getContentPane().setBackground(Color.WHITE);
        per4=p;
        der4=d;
        tit4=t;
        det_lat4=dl;
        det_prest_eco4=dp;
        det_reg4=dr;
        sol4=s;
        emp4=e;
        f4=f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtng_inc = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_tipo_seg = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_folio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_firm_essalud = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nit = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_fech_prob_part = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_vig_neonato = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rbtn_def = new javax.swing.JRadioButton();
        rbtn_prov = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txt_cob = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_vig = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_tipo_baja = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_fech_baja = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_pag_sub = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("IV. DE USO DE ESSALUD");

        jLabel2.setText("Tipo de Seguro:");

        cmb_tipo_seg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Independiente", "Potestativo", "Agrario", "Protección", "Vida" }));
        cmb_tipo_seg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipo_segActionPerformed(evt);
            }
        });

        jLabel3.setText("N° Folio Essalud:");

        jLabel4.setText("Firma y Sello de Essalud:");

        jLabel5.setText("NIT: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Madre Gestante(Hijo Extramatrimonial): ");

        jLabel7.setText("- Fecha Probable del Parto:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Neonato:");

        jLabel9.setText("- Vigencia hasta:");

        txt_vig_neonato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vig_neonatoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Hijo Mayor Incapacitado:");

        jLabel11.setText("- Incapacidad total y permanente para el trabajo");

        rbtng_inc.add(rbtn_def);
        rbtn_def.setText("Definitiva");

        rbtng_inc.add(rbtn_prov);
        rbtn_prov.setText("Provisional");
        rbtn_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_provActionPerformed(evt);
            }
        });

        jLabel12.setText("- Periodo de Cobertura:");

        jLabel13.setText("- Vigencia hasta:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Motivo de Baja:");

        jLabel15.setText("- Tipo:");

        jLabel16.setText("- Fecha desde:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Fecha de Pago del Subsidio:");

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_volver.setText("VOLVER AL MENU");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cob, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_vig, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txt_fech_prob_part, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tipo_baja, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_fech_baja, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_vig_neonato, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbtn_def))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_pag_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(rbtn_prov))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_volver))))))
                        .addGap(0, 57, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_tipo_seg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_firm_essalud, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_folio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_tipo_seg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_folio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_firm_essalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_fech_prob_part, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_vig_neonato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rbtn_def)
                    .addComponent(rbtn_prov))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_cob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txt_vig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_tipo_baja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_volver))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_fech_baja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_guardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_pag_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_provActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_provActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        String sql1,sql2,sql3,sql4,sql5,sql6;
        if(!"".equals(txt_folio.getText())){
            f4.setNro_folio(Integer.parseInt(txt_folio.getText()));
        }
        if(cmb_tipo_seg.getSelectedIndex()==0){
             f4.setTipo_seg("Regular");
        }else{
            if(cmb_tipo_seg.getSelectedIndex()==1){
                 f4.setTipo_seg("Independiente");
            }else{
                if(cmb_tipo_seg.getSelectedIndex()==2){
                    f4.setTipo_seg("Potestativo");
                }else{
                    if(cmb_tipo_seg.getSelectedIndex()==3){
                        f4.setTipo_seg("Agrario");
                    }else{
                        if(cmb_tipo_seg.getSelectedIndex()==4){
                            f4.setTipo_seg("Protección");
                        }else{
                            if(cmb_tipo_seg.getSelectedIndex()==5){
                                f4.setTipo_seg("Vida");
                            }
                        }
                    }
                }
            }
        }
        f4.setFirma_essalud(txt_firm_essalud.getText());
        if(!"".equals(txt_nit.getText())){
            f4.setNit_essalud(Integer.parseInt(txt_nit.getText()));
        }
        der4.setFech_prob_part(txt_fech_prob_part.getText());
        det_prest_eco4.setVig_neonato(txt_vig_neonato.getText());
        det_prest_eco4.setVig_hij_inc(txt_vig.getText());
        if(rbtn_def.isSelected()){
            der4.setTipo_inc_lab_hij("Definitiva");
        }else{
           if(rbtn_def.isSelected()){
                der4.setTipo_inc_lab_hij("Provisional");
            } 
        }
        if(!"".equals(txt_cob.getText())){
            det_prest_eco4.setPer_cob_hij(Integer.parseInt(txt_cob.getText()));
        }  
        det_reg4.setMotiv_baja(txt_tipo_baja.getText());
        det_reg4.setFech_motiv_baj(txt_fech_baja.getText());
        det_prest_eco4.setFech_pago_sub(txt_pag_sub.getText());
        Calendar cal= Calendar.getInstance();
        String fecha=cal.get(cal.DATE)+"-"+(cal.get(cal.MONTH)+1)+"-"+cal.get(cal.YEAR);
        String hora=cal.get(cal.HOUR_OF_DAY)+"-"+cal.get(cal.MINUTE)+"-"+cal.get(cal.SECOND); 
        String i=(fecha+"-"+hora);
        f4.setNroform(tit4.getNro_doc_per()+i);
        f4.setCod_tit_form(tit4.getCod_aseg());
        det_reg4.setCod_reg_form(f4.getNroform());
        det_lat4.setCod_form_lat(f4.getNroform());
        det_prest_eco4.setCod_prest_eco_form(f4.getNroform());
        Conectividad fun=new Conectividad(); 
        fun.conectar();
        
        sql1 ="INSERT INTO TITULAR VALUES ('"+tit4.getEst_lab_tit()+"','"+tit4.getCod_aseg()+"','"+tit4.getCod_emp_tit()+"')";
        sql3 ="INSERT INTO FORMULARIO VALUES ( '"+f4.getNroform()+"', '"+f4.getTipo_seg()+"',"+f4.getNro_folio()+",'"+f4.getCod_tit_form()+"','"+f4.getAut_correo()+"','"+f4.getFirma_essalud()+"',"+f4.getNit_essalud()+")";      
        if (der4.getCod_aseg()!=null){
            sql2="INSERT INTO DERECHOHABIENTE VALUES ('"+der4.getVin_tit_per_reg()+"','"+der4.getFech_prob_part()+"','"+der4.getTipo_inc_lab_hij()+"','"+der4.getCod_tit_der()+"','"+der4.getCod_aseg()+"')";
            insertar(sql2, fun);
        }       
        if (sol4.getCod_tit_bene()!=null){
            sql2="INSERT INTO SOLICITANTE VALUES ('"+sol4.getNro_doc_bene_prest()+"','"+sol4.getNom_bene_prest()+"',"+sol4.getTelf_bene_prest()+",'"+sol4.getCorreo_bene_prest()+"','"+sol4.getVin_bene_prest()+"','"+sol4.getFirma_bene_prest()+"','"+sol4.getCod_tit_bene()+"')";
            insertar(sql2, fun);
        }
        sql4 ="INSERT INTO DETALLE_REGISTRO VALUES ('"+det_reg4.getCod_reg_form()+"','"+det_reg4.getTipo_per_sol()+"','"+det_reg4.getTipo_reg()+"','"+det_reg4.getMotiv_baja()+"','"+det_reg4.getFech_motiv_baj()+"',"+det_reg4.getMonto_ing_neto_agro()+")";
        sql5 ="INSERT INTO DETALLE_PREST_ECO VALUES ('"+det_prest_eco4.getCod_prest_eco_form()+"','"+det_prest_eco4.getTipo_pago_prest()+"','"+det_prest_eco4.getTipo_tram_prest()+"','"+det_prest_eco4.getFech_ini_bene_prest()+"','"+det_prest_eco4.getFech_fin_bene_prest()+"',"+det_prest_eco4.getDias_subs_bene_prest()+","+det_prest_eco4.getMonto_subs()+",'"+det_prest_eco4.getFech_pago_sub()+"',"+det_prest_eco4.getPer_cob_hij()+",'"+det_prest_eco4.getVig_neonato()+"','"+det_prest_eco4.getVig_hij_inc()+"')";
        sql6 ="INSERT INTO DETALLE_LATENCIA VALUES ('"+det_lat4.getCod_form_lat()+"','"+det_lat4.getFech_susp_emp()+"')";
        insertar(sql1, fun);
        insertar(sql3, fun);
        insertar(sql4, fun);
        insertar(sql5, fun);
        insertar(sql6, fun);
        JOptionPane.showMessageDialog(null,"Se han guardado los datos proporcionados");
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void insertar(String cad, Conectividad f){
        boolean k = f.escribir(cad); 
    }
    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // TODO add your handling code here:
        Inicio in= new Inicio();
        this.setVisible(false);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void txt_vig_neonatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vig_neonatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vig_neonatoActionPerformed

    private void cmb_tipo_segActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipo_segActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipo_segActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paso4_UsodeEssalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paso4_UsodeEssalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paso4_UsodeEssalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paso4_UsodeEssalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paso4_UsodeEssalud(per4,der4,tit4,det_lat4,det_prest_eco4,det_reg4,sol4,emp4,f4).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cmb_tipo_seg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtn_def;
    private javax.swing.JRadioButton rbtn_prov;
    private javax.swing.ButtonGroup rbtng_inc;
    private javax.swing.JTextField txt_cob;
    private javax.swing.JTextField txt_fech_baja;
    private javax.swing.JTextField txt_fech_prob_part;
    private javax.swing.JTextField txt_firm_essalud;
    private javax.swing.JTextField txt_folio;
    private javax.swing.JTextField txt_nit;
    private javax.swing.JTextField txt_pag_sub;
    private javax.swing.JTextField txt_tipo_baja;
    private javax.swing.JTextField txt_vig;
    private javax.swing.JTextField txt_vig_neonato;
    // End of variables declaration//GEN-END:variables
}
